# Generated by Django 4.1.7 on 2023-04-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_new_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('data_added', models.DateTimeField(auto_now_add=True)),
                ('Theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.theme')),
            ],
        ),
    ]
