# Generated by Django 4.1.7 on 2023-04-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='Theme',
        ),
    ]
