# Generated by Django 4.1.7 on 2023-04-29 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_delete_new_chat_remove_message_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='name',
            new_name='Newchat',
        ),
    ]
