# Generated by Django 4.1.7 on 2023-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
