# Generated by Django 4.1.7 on 2023-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='res_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
