# Generated by Django 4.1.7 on 2023-05-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_message_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='role',
        ),
    ]
