# Generated by Django 4.1.7 on 2023-05-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_message_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='res_content',
        ),
    ]
